package com.aiplanner.aiprojectplanner.report;

import com.aiplanner.aiprojectplanner.dto.ProjectResponseDTO;
import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfWriter;
import org.springframework.stereotype.Component;

import java.io.ByteArrayOutputStream;

@Component
public class PDFReportGenerator {

    public byte[] generateProjectReport(ProjectResponseDTO project) {

        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();

        try {

            Document document = new Document(PageSize.A4);
            PdfWriter.getInstance(document, outputStream);

            document.open();

            // ===========================
            // Fonts
            // ===========================

            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 22);
            Font headingFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 15);
            Font bodyFont = FontFactory.getFont(FontFactory.HELVETICA, 12);

            // ===========================
            // Title
            // ===========================

            Paragraph title = new Paragraph(
                    "AI PROJECT PLANNING REPORT",
                    titleFont
            );

            title.setAlignment(Element.ALIGN_CENTER);

            document.add(title);

            document.add(new Paragraph(" "));
            document.add(new Paragraph("===================================================="));
            document.add(new Paragraph(" "));

            // ===========================
            // Project Name
            // ===========================

            addSection(document,
                    "Project Name",
                    project.getProjectName(),
                    headingFont,
                    bodyFont);

            // ===========================
            // Executive Summary
            // ===========================

            addSection(document,
                    "Executive Summary",
                    project.getExecutiveSummary(),
                    headingFont,
                    bodyFont);

            // ===========================
            // Project Objective
            // ===========================

            addSection(document,
                    "Project Objective",
                    project.getProjectObjective(),
                    headingFont,
                    bodyFont);

            // ===========================
            // Timeline
            // ===========================

            addSection(document,
                    "Timeline",
                    project.getTimeline(),
                    headingFont,
                    bodyFont);

            // ===========================
            // Resource Recommendation
            // ===========================

            addSection(document,
                    "Resource Recommendation",
                    project.getResourceRecommendation(),
                    headingFont,
                    bodyFont);

            // ===========================
            // Technology Stack
            // ===========================

            addSection(document,
                    "Technology Stack",
                    project.getTechnologyStack(),
                    headingFont,
                    bodyFont);

            // ===========================
            // Risk Analysis
            // ===========================

            addSection(document,
                    "Risk Analysis",
                    project.getRiskAnalysis(),
                    headingFont,
                    bodyFont);

            // ===========================
            // Footer
            // ===========================

            document.add(new Paragraph(" "));
            document.add(new Paragraph("===================================================="));
            document.add(new Paragraph("Generated by AI Project Planning Assistant", bodyFont));

            document.close();

        } catch (Exception e) {

            throw new RuntimeException("Failed to generate PDF report.", e);

        }

        return outputStream.toByteArray();
    }

    private void addSection(Document document,
                            String heading,
                            String content,
                            Font headingFont,
                            Font bodyFont) throws DocumentException {

        document.add(new Paragraph(heading, headingFont));

        document.add(new Paragraph(
                content != null && !content.isBlank()
                        ? content
                        : "Not Available",
                bodyFont));

        document.add(new Paragraph(" "));
    }
}